import tomatoesImg from "@/assets/tomatoes.jpg";
import maizeImg from "@/assets/maize.jpg";
import carrotsImg from "@/assets/carrots.jpg";
import lettuceImg from "@/assets/lettuce.jpg";
import potatoesImg from "@/assets/potatoes.jpg";
import spinachImg from "@/assets/spinach.jpg";

export const farmers = [
  // --- Livestock & Poultry ---
  {
    id: "livestock-1",
    name: "Sunny Poultry",
    farmer: "Anna Khumalo",
    location: "KwaZulu-Natal",
    category: "livestock",
    rating: 4.8,
    verified: true,
    description: "Free-range poultry eggs, organic-fed hens.",
    image: tomatoesImg,
    lat: -29.8587,
    lon: 31.0218,
  },
  {
    id: "livestock-2",
    name: "Nguni Beef Farm",
    farmer: "Sipho Dlamini",
    location: "North West",
    category: "livestock",
    rating: 4.9,
    verified: true,
    description: "Grass-fed Nguni beef with premium cuts.",
    image: maizeImg,
    lat: -25.6703,
    lon: 27.2421,
  },
  {
    id: "livestock-3",
    name: "Free State Chickens",
    farmer: "Johannes van Wyk",
    location: "Free State",
    category: "livestock",
    rating: 4.4,
    verified: false,
    description: "Healthy broiler chickens, well-raised on maize.",
    image: carrotsImg,
    lat: -29.1183,
    lon: 26.2140,
  },
  {
    id: "livestock-4",
    name: "Goat & Sheep Farm",
    farmer: "Maria Santos",
    location: "Limpopo",
    category: "livestock",
    rating: 4.6,
    verified: true,
    description: "Goats and sheep raised on natural pastures.",
    image: lettuceImg,
    lat: -23.9045,
    lon: 29.4689,
  },
  {
    id: "livestock-5",
    name: "Eastern Cape Livestock",
    farmer: "Nomsa Mbeki",
    location: "Eastern Cape",
    category: "livestock",
    rating: 4.5,
    verified: true,
    description: "Premium cattle and goat meat supplies.",
    image: potatoesImg,
    lat: -32.2968,
    lon: 26.4194,
  },

  // --- Grains ---
  {
    id: "grains-1",
    name: "Grains 4Lyf",
    farmer: "Johannes van der Merwe",
    location: "Free State",
    category: "grains",
    rating: 4.7,
    verified: true,
    description: "Grade 1 yellow maize, moisture content 12.5%.",
    image: maizeImg,
    lat: -28.4541,
    lon: 26.7968,
  },
  {
    id: "grains-2",
    name: "Sunshine Wheat",
    farmer: "Pieter Botha",
    location: "Western Cape",
    category: "grains",
    qualityGrade: "A+",
    price: 6.5,
    unit: "kg",
    quantity: "1.2 tons",
    rating: 4.8,
    verified: true,
    harvestDate: "2024-01-12",
    description: "High-quality wheat, perfect for bread flour.",
    image: spinachImg,
    lat: -33.9249,
    lon: 18.4241,
  },
  {
    id: "grains-3",
    name: "Mpumalanga Barley",
    farmer: "Peter Mokaba",
    location: "Mpumalanga",
    category: "grains",
    qualityGrade: "B+",
    price: 5.8,
    unit: "kg",
    quantity: "800kg available",
    rating: 4.5,
    verified: false,
    harvestDate: "2024-01-14",
    description: "Barley suitable for brewing and animal feed.",
    image: carrotsImg,
    lat: -25.4658,
    lon: 30.9853,
  },
  {
    id: "grains-4",
    name: "Northern Sun Maize",
    farmer: "David Ntuli",
    location: "Limpopo",
    category: "grains",
    qualityGrade: "A",
    price: 4.5,
    unit: "kg",
    quantity: "1.5 tons",
    rating: 4.6,
    verified: true,
    harvestDate: "2024-01-11",
    description: "Premium-grade white maize meal.",
    image: potatoesImg,
    lat: -24.1944,
    lon: 29.0097,
  },
  {
    id: "grains-5",
    name: "North West Sorghum",
    farmer: "Tshepo Molefe",
    location: "North West",
    category: "grains",
    qualityGrade: "B",
    price: 6.0,
    unit: "kg",
    quantity: "600kg available",
    rating: 4.3,
    verified: false,
    harvestDate: "2024-01-17",
    description: "Sorghum grain, suitable for beer brewing.",
    image: lettuceImg,
    lat: -25.6659,
    lon: 27.2423,
  },

  // --- Fruit & Vegetables ---
  {
    id: "fruitveg-1",
    name: "CarrotCity",
    farmer: "Maria Santos",
    location: "Western Cape",
    category: "fruit-veg",
    qualityGrade: "A+",
    price: 18.25,
    unit: "kg",
    quantity: "300kg available",
    rating: 4.8,
    verified: true,
    harvestDate: "2024-01-16",
    description: "Fresh organic carrots with excellent nutritional value.",
    image: carrotsImg,
    lat: -33.9249,
    lon: 18.4241,
  },
  {
    id: "fruitveg-2",
    name: "Fruity Town",
    farmer: "David Ntuli",
    location: "Limpopo",
    category: "fruit-veg",
    qualityGrade: "A",
    price: 15.0,
    unit: "kg",
    quantity: "200kg available",
    rating: 4.6,
    verified: true,
    harvestDate: "2024-01-12",
    description: "Fresh organic lettuce, perfect for salads.",
    image: lettuceImg,
    lat: -23.9045,
    lon: 29.4689,
  },
  {
    id: "fruitveg-3",
    name: "QualityVeggies",
    farmer: "Grace Mokoena",
    location: "Gauteng",
    category: "fruit-veg",
    qualityGrade: "B+",
    price: 12.5,
    unit: "kg",
    quantity: "150kg available",
    rating: 4.4,
    verified: false,
    harvestDate: "2024-01-14",
    description: "Quality potatoes suitable for various cooking methods.",
    image: potatoesImg,
    lat: -26.2041,
    lon: 28.0473,
  },
  {
    id: "fruitveg-4",
    name: "FreshSupplies",
    farmer: "Peter Mokaba",
    location: "Mpumalanga",
    category: "fruit-veg",
    qualityGrade: "A+",
    price: 22.0,
    unit: "kg",
    quantity: "100kg available",
    rating: 4.7,
    verified: true,
    harvestDate: "2024-01-16",
    description: "Fresh, nutrient-rich spinach leaves.",
    image: spinachImg,
    lat: -25.4658,
    lon: 30.9853,
  },
  {
    id: "fruitveg-5",
    name: "TomatoKing",
    farmer: "Lindiwe Nkosi",
    location: "KwaZulu-Natal",
    category: "fruit-veg",
    qualityGrade: "A",
    price: 20.0,
    unit: "kg",
    quantity: "500kg available",
    rating: 4.9,
    verified: true,
    harvestDate: "2024-01-18",
    description: "Juicy fresh tomatoes, perfect for sauces and stews.",
    image: tomatoesImg,
    lat: -29.6006,
    lon: 30.3794,
  },

  // --- Other ---
  {
    id: "other-1",
    name: "Organic Honey",
    farmer: "Zanele Mokoena",
    location: "Gauteng",
    category: "other",
    qualityGrade: "A",
    price: 80,
    unit: "jar",
    quantity: "300 jars",
    rating: 4.8,
    verified: true,
    harvestDate: "2024-01-09",
    description: "Pure natural honey harvested in summer.",
    image: spinachImg,
    lat: -26.2041,
    lon: 28.0473,
  },
  {
    id: "other-2",
    name: "Herbal Supplies",
    farmer: "Ahmed Khan",
    location: "Western Cape",
    category: "other",
    qualityGrade: "A+",
    price: 25,
    unit: "bundle",
    quantity: "400 bundles",
    rating: 4.6,
    verified: true,
    harvestDate: "2024-01-13",
    description: "Fresh herbs and medicinal plants.",
    image: lettuceImg,
    lat: -34.0033,
    lon: 22.4524,
  },
  {
    id: "other-3",
    name: "Cape Fish Farm",
    farmer: "John Fisher",
    location: "Western Cape",
    category: "other",
    qualityGrade: "B+",
    price: 70,
    unit: "kg",
    quantity: "500kg fish",
    rating: 4.4,
    verified: false,
    harvestDate: "2024-01-19",
    description: "Sustainably farmed tilapia and trout.",
    image: tomatoesImg,
    lat: -34.1579,
    lon: 18.8685,
  },
  {
    id: "other-4",
    name: "Rooibos Roots",
    farmer: "Thabo Mokoena",
    location: "Northern Cape",
    category: "other",
    qualityGrade: "A",
    price: 40,
    unit: "kg",
    quantity: "200kg rooibos",
    rating: 4.7,
    verified: true,
    harvestDate: "2024-01-08",
    description: "Authentic rooibos tea from Cederberg mountains.",
    image: carrotsImg,
    lat: -32.2500,
    lon: 19.2500,
  },
  {
    id: "other-5",
    name: "Wooly Supplies",
    farmer: "Jacob van Rooyen",
    location: "Free State",
    category: "other",
    qualityGrade: "A+",
    price: 55,
    unit: "kg",
    quantity: "150kg wool",
    rating: 4.5,
    verified: true,
    harvestDate: "2024-01-21",
    description: "Soft merino wool, high quality for textiles.",
    image: potatoesImg,
    lat: -29.1183,
    lon: 26.2140,
  },
];
